"""Configuration for the local BIS RAG.

Deliberately plain: this pipeline runs as ordinary Python on a workstation
with no Docker, no Postgres and no model server, because the machine it has
to run on has none of those. Everything it needs lives in one directory.
"""

from __future__ import annotations

import os
from pathlib import Path

# Source corpus (read-only — the pipeline never writes into it).
CORPUS_ROOT = Path(os.getenv("BIS_CORPUS_ROOT", r"C:\bisnew"))

# Everything the pipeline produces.
INDEX_DIR = Path(os.getenv("BIS_INDEX_DIR", str(Path(__file__).resolve().parent.parent / "rag_index")))
DB_PATH = INDEX_DIR / "bis.sqlite3"
VECTORS_PATH = INDEX_DIR / "vectors.npy"
VECTOR_IDS_PATH = INDEX_DIR / "vector_ids.npy"

# Directories under CORPUS_ROOT that hold working metadata/scripts rather than
# source documents.
EXCLUDED_DIRS = {"_meta"}

EMBEDDING_MODEL = os.getenv("BIS_EMBEDDING_MODEL", "BAAI/bge-m3")
EMBEDDING_DIM = 1024
EMBEDDING_BATCH = int(os.getenv("BIS_EMBEDDING_BATCH", "8"))
# Empty string means auto-detect: use a CUDA GPU if one is available (via
# torch), otherwise CPU. Set to "cpu" or "cuda" to force one explicitly.
EMBEDDING_DEVICE = os.getenv("BIS_EMBEDDING_DEVICE", "").strip().lower()

# Chunking. Legal text is dense and citations must stay precise, so chunks are
# kept modest and never span a page boundary — a citation that names a page
# has to be checkable on that page.
CHUNK_TARGET_CHARS = 1100
CHUNK_OVERLAP_CHARS = 180
CHUNK_MIN_CHARS = 120

# Retrieval
RRF_K = 60
DEFAULT_TOP_K = 8
CANDIDATE_K = 60

# A page whose lines are mostly rejected by the quality gate is unusable; a
# page with almost no text at all is a scan needing OCR. Both are recorded
# rather than silently dropped.
MAX_PAGE_DROP_RATIO = 0.70
MIN_PAGE_CHARS = 80

# Answering.
#
# The hosted chat completion is the ONLY part of this system that contacts a
# paid service. Extraction, indexing, embeddings and all three search modes
# run locally and cost nothing, so these knobs are the entire cost surface.
LLM_MODEL = os.getenv("BIS_LLM_MODEL", "openai/gpt-oss-20b")
LLM_BASE_URL = os.getenv("BIS_LLM_BASE_URL", "https://integrate.api.nvidia.com/v1")

# Groq serves the SAME model (openai/gpt-oss-20b) on different hardware, and
# is tried first because the difference is not subtle: measured end to end on
# this corpus, NVIDIA's shared free tier answered identical prompts anywhere
# between 9s and 250s, and the slow tail crossed the request timeout often
# enough that real questions degraded to raw quoted passages. Same weights,
# same prompt, same citation behaviour — just served fast enough that queue
# latency stops being the dominant failure mode.
#
# NVIDIA stays configured as the fallback rather than being replaced: Groq's
# free tier is capped per-minute (8k tokens) and per-day (200k), so a busy
# demo can exhaust it, and a slow answer beats no answer.
GROQ_BASE_URL = os.getenv("BIS_GROQ_BASE_URL", "https://api.groq.com/openai/v1")
GROQ_MODEL = os.getenv("BIS_GROQ_MODEL", "openai/gpt-oss-20b")
# gpt-oss-20b is a reasoning model: part of this budget is spent on hidden
# chain-of-thought before it writes the visible answer, so the budget has to
# cover BOTH. 1200, then 1800, then 3000 all proved too tight — observed
# failing with finish_reason=length (whole budget consumed thinking, zero
# visible answer) on multi-part questions such as "which standard applies,
# is certification mandatory, which scheme, what testing is required" — one
# question bundling several sub-questions needs a long structured reply.
# Starting higher means fewer questions ever need the doubling escalation
# below, which is what was pushing multi-part questions past the total
# deadline and into the raw-quotes fallback instead of a real summary.
LLM_MAX_TOKENS = int(os.getenv("BIS_LLM_MAX_TOKENS", "4500"))
# When a call dies from budget exhaustion, `llm.chat` doubles the budget and
# retries rather than repeating an identical, certain-to-fail request. This
# caps that escalation so a pathological question cannot grow without bound.
LLM_MAX_TOKENS_CEILING = int(os.getenv("BIS_LLM_MAX_TOKENS_CEILING", "8000"))

# Master switch. False means no code path can reach the network at all.
LLM_ENABLED = os.getenv("BIS_LLM_ENABLED", "true").strip().lower() not in {
    "false", "0", "no", "off",
}
# Hard daily cap, enforced locally before a request is sent. Raised for
# demo days: several people testing in parallel can burn 200 quickly, and
# hitting the cap mid-demo silently downgrades every answer to extracts.
# The real runaway guard is LLM_MAX_ATTEMPTS_PER_QUESTION below — that is
# what stops one question becoming a storm of requests.
LLM_DAILY_CALL_LIMIT = int(os.getenv("BIS_LLM_DAILY_CALL_LIMIT", "600"))
# Upper bound on requests generated by ONE question, across retries and model
# fallbacks. Without this, a provider outage turns a single question into a
# storm of billable requests.
LLM_MAX_ATTEMPTS_PER_QUESTION = int(os.getenv("BIS_LLM_MAX_ATTEMPTS", "4"))

# How long any single request may hang before it is abandoned.
# Measured against this provider: a normal grounded answer takes 20-55s, and
# the spread is driven by NVIDIA's shared free-tier queueing rather than by
# prompt size — a SMALLER prompt measured slower (7,706 chars -> 54.5s) than a
# larger one (13,206 chars -> 36.9s). So this cannot be tuned down. It was set
# to 45s and that was worse than useless: it cut off answers that were
# legitimately still generating and downgraded them to bare extracts.
LLM_REQUEST_TIMEOUT = int(os.getenv("BIS_LLM_REQUEST_TIMEOUT", "100"))
# Hard ceiling on the wall-clock a user can spend waiting for one question.
# Past this, no further attempt is started and the answer falls back to the
# local extractive path, which is instant.
#
# This exists for live use. With a 180s per-request timeout and 3 attempts,
# a provider slowdown meant a 540-second spinner — nine minutes of a person
# staring at a loading indicator before getting anything at all. A fast,
# honest fallback beats a perfect answer nobody waits for.
#
# Raised from 130s: at 130s, a multi-part question (e.g. "which standard,
# is certification mandatory, which scheme, what testing") that needed the
# token-budget escalation ladder (LLM_MAX_TOKENS -> doubled -> doubled again)
# usually only got time for one 100s attempt before the deadline cut it off,
# so it fell back to raw quoted passages even though the model would have
# answered fine on the next escalated attempt. 190s leaves room for that
# ladder to actually run instead of being cut off after its first rung.
LLM_TOTAL_DEADLINE = int(os.getenv("BIS_LLM_TOTAL_DEADLINE", "190"))


def load_env_file(path: Path) -> dict[str, str]:
    """Read a .env file into a dict without mutating os.environ."""
    values: dict[str, str] = {}
    if not path.exists():
        return values
    for line in path.read_text(encoding="utf-8", errors="replace").splitlines():
        line = line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, raw = line.split("=", 1)
        values[key.strip()] = raw.split("#")[0].strip()
    return values


def llm_api_key() -> str:
    """API key from the environment, falling back to the project .env."""
    key = os.getenv("BIS_LLM_API_KEY") or os.getenv("HOSTED_LLM_API_KEY")
    if key:
        return key
    env_path = Path(__file__).resolve().parent.parent / ".env"
    return load_env_file(env_path).get("HOSTED_LLM_API_KEY", "")


def groq_api_key() -> str:
    """Groq API key, or "" when none is configured — in which case the
    provider is skipped entirely rather than attempted and failed."""
    key = os.getenv("GROQ_API_KEY")
    if key:
        return key
    env_path = Path(__file__).resolve().parent.parent / ".env"
    return load_env_file(env_path).get("GROQ_API_KEY", "")
