import type { DisplayMessage } from "@/hooks/useChatStream";

/**
 * Render a transcript as Markdown, with each answer's cited sources listed
 * beneath it.
 *
 * Sources are emitted per-answer rather than pooled into one bibliography
 * at the end: the `[N]` markers restart at 1 for every answer (they index
 * into that answer's own retrieved context), so a single combined list
 * would collide numbers between turns.
 */
export function conversationToMarkdown(messages: DisplayMessage[]): string {
  const lines: string[] = ["# Manak Sahayak conversation", ""];
  lines.push(`_Exported ${new Date().toLocaleString()}_`, "");

  for (const message of messages) {
    if (message.role === "user") {
      lines.push(`## Question`, "", message.content, "");
      continue;
    }

    lines.push(`### Answer`, "", message.content, "");

    if (message.citations?.length) {
      lines.push("**Sources**", "");
      for (const citation of message.citations) {
        const label = citation.is_number ?? citation.document_title ?? "Untitled source";
        const clause = citation.clause_number ? `, clause ${citation.clause_number}` : "";
        const url = citation.document_source_url ? ` — ${citation.document_source_url}` : "";
        lines.push(`- [${citation.marker}] ${label}${clause}${url}`);
      }
      lines.push("");
    }

    if (message.forcedRefusal) {
      lines.push("> Not answered from an LLM — nothing was found in indexed sources.", "");
    }
  }

  lines.push(
    "---",
    "",
    "Generated by Manak Sahayak (SIH26107). Answers are grounded in indexed BIS sources; " +
      "confirm anything consequential with BIS directly.",
  );

  return lines.join("\n");
}

/** Trigger a client-side download of `content` as a file. */
export function downloadTextFile(filename: string, content: string): void {
  const blob = new Blob([content], { type: "text/markdown;charset=utf-8" });
  const url = URL.createObjectURL(blob);
  const anchor = document.createElement("a");
  anchor.href = url;
  anchor.download = filename;
  document.body.appendChild(anchor);
  anchor.click();
  document.body.removeChild(anchor);
  // Revoking immediately can race the download in some browsers; a tick is
  // enough for the click to have been handled.
  window.setTimeout(() => URL.revokeObjectURL(url), 0);
}
